apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-darling-terrier
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "289636418460"
    provider: eks
    region: eu-west-1
    registry: 289636418460.dkr.ecr.eu-west-1.amazonaws.com
  environments:
  - key: dev
    owner: artemfindir
    repository: jx-cluster
  - key: staging
  - key: production
  ingress:
    domain: 52.50.49.208.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: ait-af-bot
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-tf-jx-darling-terrier-20211022105456959100000002
  - name: reports
    url: s3://reports-tf-jx-darling-terrier-20211022105456960500000003
  - name: repository
    url: s3://repository-tf-jx-darling-terrier-20211022105456962400000004
  terraform: true
  vault:
    aws:
      dynamoDBRegion: eu-west-1
      dynamoDBTable: vault-unseal-tf-jx-darling-terrier-OjKBkcKF
      kmsKeyId: dbbf3948-2d21-4d42-8066-2bc7f4a70e0f
      kmsRegion: eu-west-1
      s3Bucket: vault-unseal-tf-jx-darling-terrier-20211022105456962800000006
      s3Region: eu-west-1
  webhook: lighthouse
