filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-staging
repositories:
- name: dev
  url: http://chartmuseum-jx.18.203.76.151.nip.io
releases:
- chart: dev/quick-py-project
  version: 0.0.2
  name: quick-py-project
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
