apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        ait-af-bot/af-jx-java-clock: true
        ait-af-bot/quick-py-project: true
        artemfindir/jx-cluster: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        ait-af-bot/af-jx-java-clock: merge
        ait-af-bot/quick-py-project: merge
        artemfindir/jx-cluster: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - artemfindir/jx-cluster
        - ait-af-bot/af-jx-java-clock
        - ait-af-bot/quick-py-project
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - artemfindir/jx-cluster
        - ait-af-bot/af-jx-java-clock
        - ait-af-bot/quick-py-project
      target_url: http://lighthouse-jx.18.203.76.151.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
